-- DROP TABLE IF EXISTS user;

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age INT NULL DEFAULT NULL COMMENT '年龄',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱'
);